### ISSUE TITLE
Feature Request: More than two players

### ISSUE THREAD

**Issue by Olfi01** [markozajc/JUNO#10]
As mentioned in the title, it would be great if the library could support uno games with more than two players.
Regardless, I love what you've done here!

**Comment by markozajc** [comment]
I'll look into it. It should be possible, but I would likely need to rewrite a portion of the library to support it (implementing proper flow control via skip and reverse cards, adding support for it in the rule classes, etc).

**Comment by Olfi01** [comment]
Nice! I'm taking a poke at it on a fork too, just for fun :D

**Comment by Olfi01** [comment]
Done as of 2.3
